name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.16
  - pandas=1.3.5
  - pytest=7.4.4
  - scipy=1.5.2
  - pip=23.3.1
  - pip:
      - mlflow==1.26.0
      - wandb==0.16.0
